"""The agent-facing self-describing layer: index.json + llms.txt.

The staleness gate (validate.yml / check_all.py) only proves committed ==
regenerated; since both run the same code, it can't catch a bug in the
GENERATOR. These tests run the generator in-process over the committed manifest
and pin its invariants, so a future manifest/schema change that breaks the
projection fails here instead of silently shipping a malformed index. (They do
NOT read a committed index.json -- it is a deploy-time artifact, regenerated by
pages.yml, and CI runs pytest before the build step.)
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))

from build_catalog import build_agent_index, render_llms_txt  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = json.loads((ROOT / "catalog.json").read_text())
INDEX = build_agent_index(MANIFEST)
LLMS = render_llms_txt(MANIFEST)


def test_index_counts_match_manifest():
    for key in ("n_parts", "n_validated", "n_candidate", "n_functional_claims"):
        assert INDEX[key] == MANIFEST[key], key
    assert len(INDEX["parts"]) == MANIFEST["n_parts"]


def test_index_part_set_and_fields_mirror_manifest():
    by_slug = {p["slug"]: p for p in MANIFEST["parts"]}
    assert {p["slug"] for p in INDEX["parts"]} == set(by_slug)
    for entry in INDEX["parts"]:
        src = by_slug[entry["slug"]]
        # The claim count is the agent's trust/coverage signal -- it must be exact.
        assert entry["n_claims"] == len(src.get("functional_claims", [])), entry["slug"]
        for field in ("name", "feature_type", "kind", "so_term", "status"):
            assert entry[field] == src[field], (entry["slug"], field)


def test_index_collections_match_manifest():
    cat = {c["id"]: c["n_parts"] for c in MANIFEST["collections"]}
    idx = {c["id"]: c["n_parts"] for c in INDEX["collections"]}
    assert idx == cat


def test_url_templates_well_formed():
    t = INDEX["url_templates"]
    for key in ("iri", "page", "record", "genbank", "fasta", "rdf"):
        assert "{slug}" in t[key], key
    assert INDEX["base_iri"].startswith("https://w3id.org/seqmake/parts")
    assert INDEX["catalog"].endswith("/catalog.json")


def test_llms_txt_carries_live_counts_and_entry_urls():
    assert str(MANIFEST["n_parts"]) in LLMS
    for url in (f"{INDEX['base_iri']}/index.json",
                f"{INDEX['base_iri']}/catalog.json",
                f"{INDEX['base_iri']}/schema/part.schema.json"):
        assert url in LLMS, url
    # The trust caveat is the contract with consumers -- it must stay present.
    assert "pending" in LLMS and "VERIFY" in LLMS
